/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MeRouteImport } from './routes/me'
import { Route as PathRouteImport } from './routes/path'
import { Route as SpeakRouteImport } from './routes/speak'
import { Route as LessonIdRouteImport } from './routes/lesson/$id'
import { Route as SpeakIndexRouteImport } from './routes/speak/index'
import { Route as SpeakIdRouteImport } from './routes/speak/$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const PathRoute = PathRouteImport.update({
  id: '/path',
  path: '/path',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeakRoute = SpeakRouteImport.update({
  id: '/speak',
  path: '/speak',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonIdRoute = LessonIdRouteImport.update({
  id: '/lesson/$id',
  path: '/lesson/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeakIndexRoute = SpeakIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SpeakRoute,
} as any)
const SpeakIdRoute = SpeakIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SpeakRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/path': typeof PathRoute
  '/speak': typeof SpeakRouteWithChildren
  '/lesson/$id': typeof LessonIdRoute
  '/speak/$id': typeof SpeakIdRoute
  '/speak/': typeof SpeakIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/path': typeof PathRoute
  '/lesson/$id': typeof LessonIdRoute
  '/speak/$id': typeof SpeakIdRoute
  '/speak': typeof SpeakIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/path': typeof PathRoute
  '/speak': typeof SpeakRouteWithChildren
  '/lesson/$id': typeof LessonIdRoute
  '/speak/$id': typeof SpeakIdRoute
  '/speak/': typeof SpeakIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/me'
    | '/path'
    | '/speak'
    | '/lesson/$id'
    | '/speak/$id'
    | '/speak/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/me'
    | '/path'
    | '/lesson/$id'
    | '/speak/$id'
    | '/speak'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/me'
    | '/path'
    | '/speak'
    | '/lesson/$id'
    | '/speak/$id'
    | '/speak/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  MeRoute: typeof MeRoute
  PathRoute: typeof PathRoute
  SpeakRoute: typeof SpeakRouteWithChildren
  LessonIdRoute: typeof LessonIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/path': {
      id: '/path'
      path: '/path'
      fullPath: '/path'
      preLoaderRoute: typeof PathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speak': {
      id: '/speak'
      path: '/speak'
      fullPath: '/speak'
      preLoaderRoute: typeof SpeakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson/$id': {
      id: '/lesson/$id'
      path: '/lesson/$id'
      fullPath: '/lesson/$id'
      preLoaderRoute: typeof LessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speak/': {
      id: '/speak/'
      path: '/'
      fullPath: '/speak/'
      preLoaderRoute: typeof SpeakIndexRouteImport
      parentRoute: typeof SpeakRoute
    }
    '/speak/$id': {
      id: '/speak/$id'
      path: '/$id'
      fullPath: '/speak/$id'
      preLoaderRoute: typeof SpeakIdRouteImport
      parentRoute: typeof SpeakRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SpeakRouteChildren {
  SpeakIdRoute: typeof SpeakIdRoute
  SpeakIndexRoute: typeof SpeakIndexRoute
}

const SpeakRouteChildren: SpeakRouteChildren = {
  SpeakIdRoute: SpeakIdRoute,
  SpeakIndexRoute: SpeakIndexRoute,
}

const SpeakRouteWithChildren = SpeakRoute._addFileChildren(SpeakRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  MeRoute: MeRoute,
  PathRoute: PathRoute,
  SpeakRoute: SpeakRouteWithChildren,
  LessonIdRoute: LessonIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
